<a href="https://colab.research.google.com/github/Aniaannaan/ObliczeniaNaukowe/blob/main/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Zadanie 1

In [3]:
import numpy as np
np.linspace(0,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
def calka (funkcja,a,b,N):
  podzial=np.linspace(a,b,N)
  podstawa=(b-a)/(N-1)
  wartosc=0
  for i in range(N-1):
    wartosc+=podstawa*abs(funkcja(podzial[i]))
  return wartosc


In [10]:
calka(lambda x:x**2,0,1,1000)

0.33283299983333353

NumPy-Zadanie3

In [15]:
tab=np.array([[1,2], [3,4],[4,1]])  #tablica

In [16]:
tab.nbytes  #rozmiar tablicy

48

In [17]:
tab.shape #wymiary tablicy

(3, 2)

In [18]:
tab.ndim 

2

In [19]:
tab.size

6

In [20]:
tab.dtype

dtype('int64')

In [22]:
tab2=np.array(tab,dtype=float)
tab2

array([[1., 2.],
       [3., 4.],
       [4., 1.]])

In [24]:
tab3=np.array([-1,0,1])

In [25]:
np.sqrt(tab3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [29]:
tab4=tab3.astype(complex)   #zamiana int na zespolone
tab4
np.sqrt(tab4).imag #czesci urojone

array([1., 0., 0.])

Konstruktory

In [30]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.meshgrid([1,2,3],['a', 'b', 'c'])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([['a', 'a', 'a'],
        ['b', 'b', 'b'],
        ['c', 'c', 'c']], dtype='<U1')]

Zadanie 4

In [37]:
from scipy.linalg import block_diag
Mat1=block_diag(np.ones((2,2)),np.zeros((2,2)),3,(4*np.ones((2,2))-2*np.diag((1,1))))  #lub mp.eye(2)
Mat1

array([[1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [39]:
Mat1[0,0]=3
Mat1

array([[3., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [41]:
Mat1[1:3,1:3] #obcinanie

array([[1., 0.],
       [0., 0.]])

In [43]:
Mat1[:, ::-1] #odwrotnie

array([[0., 0., 0., 0., 0., 1., 3.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0.],
       [4., 2., 0., 0., 0., 0., 0.],
       [2., 4., 0., 0., 0., 0., 0.]])

Zadanie 5

In [46]:
Mat1[:4, :4]

array([[3., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
Mat1[-3:, -3:]

array([[3., 0., 0.],
       [0., 2., 4.],
       [0., 4., 2.]])

In [51]:
block_diag(Mat1[-3:,-3:],Mat1[:4,:4])

array([[3., 0., 0., 0., 0., 0., 0.],
       [0., 2., 4., 0., 0., 0., 0.],
       [0., 4., 2., 0., 0., 0., 0.],
       [0., 0., 0., 3., 1., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

Zadanie 6

In [54]:
Mat3=Mat1[1::2, 1::2]
Mat3

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 2.]])