<a href="https://colab.research.google.com/github/Aniaannaan/ObliczeniaNaukowe/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import block_diag

In [2]:
Mat1=block_diag(np.ones((2,2)),np.zeros((2,2)),3,(4*np.ones((2,2))-2*np.eye(2)))

In [3]:
Mat1.shape

(7, 7)

In [5]:
Mat1.reshape((1,49)) #zmiana kształtu

array([[1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        3., 0., 0., 0., 0., 0., 0., 0., 2., 4., 0., 0., 0., 0., 0., 4.,
        2.]])

In [10]:
tab=np.array([[1,2,3],[2,3,4]])
tab

array([[1, 2, 3],
       [2, 3, 4]])

In [11]:
tab.reshape((3,2))

array([[1, 2],
       [3, 2],
       [3, 4]])

In [12]:
tab.reshape((1,6))

array([[1, 2, 3, 2, 3, 4]])

In [13]:
tab.reshape(-1) #gdy nie znamy wymiaru

array([1, 2, 3, 2, 3, 4])

### Zadanie 7
Utwórz tablicę

$$
\begin{bmatrix}
1&2&3&4\\
5&6&7&8 \\
9&10&11&12\\
13&14&15&16
\end{bmatrix}
$$

In [15]:
tab=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
tab

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

lub szybciej

In [16]:
np.arange(1,17).reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#Zadanie
Utwórz macierz o wymiarach 5x6x3 i elementach
X[i,j,k]=100+60(i-1)+10(j-1)+300(k-1)

ValueError: ignored

Dodawanie macierzy

In [24]:
tab1=np.array([1,2])
tab1

array([1, 2])

In [25]:
tab2=np.array([[1],[2]])
tab2

array([[1],
       [2]])

In [27]:
tab1+tab2

array([[2, 3],
       [3, 4]])

Dodawanie macierzy czy sie da

In [30]:
tab3=np.zeros((2,4))
tab3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
tab4=np.ones((2,2))
tab4

array([[1., 1.],
       [1., 1.]])

In [32]:
tab3+tab4

ValueError: ignored

In [35]:
2*np.eye(2)*np.ones((2,2))

array([[2., 0.],
       [0., 2.]])

In [36]:
np.sin(tab2)

array([[0.84147098],
       [0.90929743]])

In [40]:
tab1=np.array([[1,2],[3,4]])
tab2=np.array([[5,6],[6,7]])
tab2**tab1

array([[   5,   36],
       [ 216, 2401]])

In [43]:
A=np.arange(1,17).reshape((2,8))

In [44]:
A.T #transpozycja

array([[ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15],
       [ 8, 16]])

Agregascja

In [45]:
A=np.arange(1,17).reshape((2,8))
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [46]:
np.mean(A) #średnia

8.5

In [47]:
np.mean(A,axis=0) #średnia po kolumnach

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [48]:
np.mean(A,axis=1) #średnia po wierszach

array([ 4.5, 12.5])

In [50]:
k=np.random.random(100)
k

array([0.61662132, 0.11089006, 0.02748938, 0.32857192, 0.85506299,
       0.89289207, 0.80122557, 0.90801236, 0.0467619 , 0.13289151,
       0.32655557, 0.07740316, 0.12804834, 0.63292643, 0.40638254,
       0.2235916 , 0.37374504, 0.4200141 , 0.87050175, 0.44478459,
       0.9246794 , 0.11715285, 0.47543813, 0.64125879, 0.73130072,
       0.08667999, 0.10503334, 0.87696035, 0.25457725, 0.30105211,
       0.94098234, 0.35567401, 0.22182721, 0.28523588, 0.59363574,
       0.08978105, 0.9194256 , 0.96930379, 0.01919173, 0.2568135 ,
       0.9676128 , 0.25584365, 0.46380086, 0.13417112, 0.48084408,
       0.97136415, 0.20222235, 0.84561377, 0.28373699, 0.3165736 ,
       0.82550644, 0.05480392, 0.10445739, 0.47843945, 0.12431329,
       0.79016389, 0.66717729, 0.69029026, 0.59215284, 0.39043629,
       0.24740971, 0.35092677, 0.59829049, 0.54470698, 0.75627763,
       0.45815949, 0.4740906 , 0.64736936, 0.77520591, 0.98220954,
       0.47156137, 0.18777982, 0.35064597, 0.30020089, 0.22014

In [52]:
np.sum(k)

48.19044736099545

In [53]:
np.cumsum(A) #skumulowana suma tablica po kolumnach

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136])

In [54]:
np.cumsum(A, axis=1) #skumulowana suma po wierszach

array([[  1,   3,   6,  10,  15,  21,  28,  36],
       [  9,  19,  30,  42,  55,  69,  84, 100]])

In [55]:
A>5 #czy dana wartość maierzy jest wieksza od 5

array([[False, False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [56]:
A[A>5] #macierz elementów większych od 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [58]:
A*(A>5) #mnożenienie macierzy 

array([[ 0,  0,  0,  0,  0,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [59]:
if np.any(A>5): # czy są jakieś elementy wieksze od 5
  print('tak')

tak


In [60]:
if np.all(A>5): # czy wszystkie elementy wieksze od 5
  print('tak')

In [62]:
L=np.arange(1,17).reshape(4,4)
L

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [63]:
x=np.array([1,2,3,4])
y=np.array([0,4,1,6])

In [64]:
x<y

array([False,  True, False,  True])

In [65]:
L[x<y]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

#Algebra liniowa w pythonie

In [67]:
A=np.array([[2,3],[0,2]])
A

array([[2, 3],
       [0, 2]])

In [69]:
B=np.array([[2,5],[3,8]])
B

array([[2, 5],
       [3, 8]])

In [80]:
D=np.linalg.inv(B)
D

array([[ 8., -5.],
       [-3.,  2.]])

In [93]:
C=np.dot(B,np.dot(A,np.linalg.inv(B))) #BAB^-1
C

array([[-16.,  12.],
       [-27.,  20.]])

In [88]:
np.linalg.eig(A)[0] #wektor własny

array([2., 2.])

In [89]:
np.linalg.eig(A)[1]

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  1.48029737e-16]])

In [90]:
np.linalg.eig(A)[1][:,0]

array([1., 0.])

In [94]:
np.linalg.eig(C)[0] 

array([2.+1.97405238e-07j, 2.-1.97405238e-07j])