<a href="https://colab.research.google.com/github/Aniaannaan/ObliczeniaNaukowe/blob/main/Lab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#np.linalg.inv - odwrotność macierzy
#np.linalg.det - wyznacznik
#np.linalg.eig - wartości i wektory własne
#np.dot - iloczyn macierzowy
#np.inner - iloczyn skalarny
#np.cross - iloczyn wektorowy

#np.linalg.norm - norma macierzy lub wektora

In [4]:
import numpy as np
n=np.random.randint(low=0, high=10, size=(5,5))
n

array([[5, 7, 9, 4, 2],
       [4, 8, 6, 5, 7],
       [1, 6, 3, 0, 0],
       [6, 8, 3, 7, 5],
       [0, 3, 5, 7, 9]])

In [6]:
%timeit np.linalg.eig(n)

The slowest run took 41.80 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 33.6 µs per loop


In [8]:
M=np.linalg.eig(n)
M

(array([24.05262028+0.j        , -1.0110187 +2.40740181j,
        -1.0110187 -2.40740181j,  4.98470856+1.52910623j,
         4.98470856-1.52910623j]),
 array([[-0.4394982 +0.j        ,  0.54313136+0.j        ,
          0.54313136-0.j        , -0.59374167-0.00282003j,
         -0.59374167+0.00282003j],
        [-0.53320635+0.j        , -0.15679009-0.29861668j,
         -0.15679009+0.29861668j,  0.11930899-0.07440196j,
          0.11930899+0.07440196j],
        [-0.17284007+0.j        , -0.1242251 +0.37213498j,
         -0.1242251 -0.37213498j, -0.07082194-0.17178217j,
         -0.07082194+0.17178217j],
        [-0.55946997+0.j        , -0.48631228+0.00996188j,
         -0.48631228-0.00996188j, -0.35546945+0.28975057j,
         -0.35546945-0.28975057j],
        [-0.42385372+0.j        ,  0.44801648+0.00439492j,
          0.44801648-0.00439492j,  0.61875181+0.j        ,
          0.61875181-0.j        ]]))

In [11]:
type(M)

tuple

In [14]:
np.max(M[0])

(24.052620277113718+0j)

In [18]:
tab=np.array([[2,3],[4,5]])
tab

array([[2, 3],
       [4, 5]])

In [20]:
np.linalg.det(tab)

-2.0

In [29]:
c=np.dot(tab,np.dot(np.diag([2,3]),np.linalg.inv(tab)))
c

array([[ 8., -3.],
       [10., -3.]])

In [28]:
np.linalg.eig(c)

(array([3., 2.]), array([[0.51449576, 0.4472136 ],
        [0.85749293, 0.89442719]]))

In [34]:
tab @ tab

array([[16, 21],
       [28, 37]])

In [33]:
np.dot(tab, tab)

array([[16, 21],
       [28, 37]])

SVD

In [37]:
SVD=np.linalg.svd(n) #rozkład svd
SVD

(array([[-0.47919694,  0.48244684, -0.50160249, -0.53040248, -0.06843597],
        [-0.53739063, -0.03426227,  0.00998944,  0.3457592 ,  0.76836723],
        [-0.19745616,  0.4460667 , -0.10409678,  0.74065477, -0.45014435],
        [-0.50696575,  0.04530329,  0.79006   , -0.21351446, -0.26673979],
        [-0.43078811, -0.75169359, -0.33654749,  0.0704689 , -0.36214399]]),
 array([25.49204299,  8.45261513,  4.93973402,  3.26541267,  1.28263382]),
 array([[-0.30538148, -0.55650035, -0.4630591 , -0.43809819, -0.43668725],
        [ 0.35410007,  0.45983112,  0.21911444, -0.37695506, -0.68779519],
        [ 0.43893224,  0.25405313, -0.82582049,  0.24659725, -0.00241031],
        [-0.554113  ,  0.61262574, -0.234366  , -0.42693926,  0.2836264 ],
        [ 0.53070949, -0.19750797,  0.02565599, -0.65029803,  0.50575911]]))

In [40]:
SVD[0] @ np.diag(SVD[1]) @ SVD[2]-n

array([[ 0.00000000e+00, -8.88178420e-16, -3.55271368e-15,
         0.00000000e+00, -2.88657986e-15],
       [ 1.77635684e-15,  0.00000000e+00,  0.00000000e+00,
         1.77635684e-15,  0.00000000e+00],
       [-3.33066907e-16,  0.00000000e+00,  2.22044605e-15,
        -9.72726062e-17,  6.94893506e-16],
       [-8.88178420e-16, -3.55271368e-15, -3.99680289e-15,
         0.00000000e+00, -1.77635684e-15],
       [ 1.28161174e-15,  3.10862447e-15,  8.88178420e-16,
         8.88178420e-16,  0.00000000e+00]])

In [43]:
(SVD[0] @ SVD[0].T).round(0)

array([[ 1., -0.,  0.,  0.,  0.],
       [-0.,  1., -0.,  0., -0.],
       [ 0., -0.,  1., -0.,  0.],
       [ 0.,  0., -0.,  1., -0.],
       [ 0., -0.,  0., -0.,  1.]])

In [44]:
M=np.array([[1,2,3],[1,2,1],[0,1,0]])
M

array([[1, 2, 3],
       [1, 2, 1],
       [0, 1, 0]])

In [45]:
np.linalg.eig(M)

(array([ 3.45667834+0.j        , -0.22833917+0.72556968j,
        -0.22833917-0.72556968j]),
 array([[ 0.74635087+0.j        , -0.85289345+0.j        ,
         -0.85289345-0.j        ],
        [ 0.63933662+0.j        ,  0.21479077+0.23188188j,
          0.21479077-0.23188188j],
        [ 0.18495693+0.j        ,  0.20602029-0.36086579j,
          0.20602029+0.36086579j]]))

In [47]:
SVD=np.linalg.svd(M)
SVD

(array([[-0.8384388 , -0.50673863, -0.20058996],
        [-0.52438113,  0.6498237 ,  0.55023049],
        [-0.14847494,  0.56652018, -0.81056158]]),
 array([4.39972444, 1.22684012, 0.37052417]),
 array([[-0.3097512 , -0.65324882, -0.69088362],
        [ 0.11662894,  0.69502969, -0.70945854],
        [ 0.94363758, -0.30033266, -0.13909856]]))

In [67]:
N=M[0:2]
N

array([[1, 2, 3],
       [1, 2, 1]])

In [68]:
SVD=np.linalg.svd(N)
SVD

(array([[-0.85065081, -0.52573111],
        [-0.52573111,  0.85065081]]),
 array([4.3525018, 1.0274863]),
 array([[-3.16227766e-01, -6.32455532e-01, -7.07106781e-01],
        [ 3.16227766e-01,  6.32455532e-01, -7.07106781e-01],
        [-8.94427191e-01,  4.47213595e-01, -2.22044605e-16]]))

In [69]:
np.concatenate([N,N]) #łączenie macierzy

array([[1, 2, 3],
       [1, 2, 1],
       [1, 2, 3],
       [1, 2, 1]])

In [70]:
a=np.diag(SVD[1])
a

array([[4.3525018, 0.       ],
       [0.       , 1.0274863]])

In [71]:
b=np.concatenate([a,np.zeros((2,1))],axis=1)
b #łączenie macierzy kolumnami

array([[4.3525018, 0.       , 0.       ],
       [0.       , 1.0274863, 0.       ]])

In [72]:
SVD[0] @ b @ SVD[2]

array([[1., 2., 3.],
       [1., 2., 1.]])

Zadanie

In [73]:
M=np.array([[1,2,3],[1,2,1],[0,1,0]])
M

array([[1, 2, 3],
       [1, 2, 1],
       [0, 1, 0]])

In [78]:
np.linalg.matrix_power(M,20)

array([[16968908951, 41687151125, 26786952325],
       [14535850675, 35709909551, 22946150525],
       [ 4205149925, 10330700750,  6638208201]])

In [81]:
A=np.linalg.eig(M)
A

(array([ 3.45667834+0.j        , -0.22833917+0.72556968j,
        -0.22833917-0.72556968j]),
 array([[ 0.74635087+0.j        , -0.85289345+0.j        ,
         -0.85289345-0.j        ],
        [ 0.63933662+0.j        ,  0.21479077+0.23188188j,
          0.21479077-0.23188188j],
        [ 0.18495693+0.j        ,  0.20602029-0.36086579j,
          0.20602029+0.36086579j]]))

In [83]:
JA=np.diag(A[0])
JA

array([[ 3.45667834+0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        , -0.22833917+0.72556968j,
         0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
        -0.22833917-0.72556968j]])

In [85]:
P=A[1]
P

array([[ 0.74635087+0.j        , -0.85289345+0.j        ,
        -0.85289345-0.j        ],
       [ 0.63933662+0.j        ,  0.21479077+0.23188188j,
         0.21479077-0.23188188j],
       [ 0.18495693+0.j        ,  0.20602029-0.36086579j,
         0.20602029+0.36086579j]])

In [86]:
P @ JA**20 @ np.linalg.inv(P)

array([[1.69689090e+10-1.64637822e-06j, 4.16871511e+10+3.29275644e-06j,
        2.67869523e+10+7.78525577e-20j],
       [1.45358507e+10-1.41031507e-06j, 3.57099096e+10+2.82063013e-06j,
        2.29461505e+10-8.64595148e-21j],
       [4.20514992e+09-4.07997195e-07j, 1.03307007e+10+8.15994389e-07j,
        6.63820820e+09+4.10216869e-20j]])

#Rozwiązywanie układów równań
````np.linalg.cond ````- współczynnik uwarunkowania

````np.linalg.solve````- rozwiązywania równania macierzowegp

In [87]:
np.linalg.cond(M)

11.87432495287239

In [90]:
A=np.array([[1,0,2],[3,2,1],[1,1,1]])
A
np.linalg.cond(A)

10.617346008950063

In [92]:
b1=np.array([20.001,-9.9999,100.00001])
b1

array([ 20.001  ,  -9.9999 , 100.00001])

In [93]:
b2=np.array([20,-10,100])
b2

array([ 20, -10, 100])

In [95]:
np.linalg.solve(A,b1)

array([-133.33294667,  156.66598333,   76.66697333])

In [94]:
,np.linalg.solve(A,b2)

array([-133.33333333,  156.66666667,   76.66666667])