<a href="https://colab.research.google.com/github/Aniaannaan/ObliczeniaNaukowe/blob/main/Regresja_liniowa25.05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Regresja liniowa

In [5]:
from sklearn import datasets #zbiory danych
from sklearn import model_selection ##podział danyc na uczace i testowe
from sklearn import linear_model
from sklearn import metrics #miary do oceny pracy modelu
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [6]:
x_all,y_all=datasets.make_regression(n_samples=50,n_features=50,n_informative=10)

In [7]:
x_all.shape

(50, 50)

In [8]:
y_all.shape

(50,)

In [9]:
X_train,X_test,Y_train,Y_test=model_selection.train_test_split(x_all,y_all,test_size=25)

In [10]:
X_train.shape

(25, 50)

In [11]:
model=linear_model.LinearRegression()

In [14]:
model.fit(X_train,Y_train)

LinearRegression()

In [18]:
Y_predict=model.predict(X_test)
Y_predict

array([ -53.74629162,  -79.37207381, -233.62252886,   33.34069594,
       -190.20099736,   75.70690443,  -93.83759928,   75.56035021,
         15.93460126, -129.41398646,  -14.86807605,   19.42115152,
        -86.52218499,  -55.82607136, -244.18255503,  -25.43718797,
         17.2522714 , -165.53025457, -226.70540114,  -61.77072911,
         22.94306954,  160.49741323,  107.38457956,  -18.12660329,
         40.81067626])

In [23]:
Y_test-Y_predict

array([ 178.73545879,   75.74219234,  -65.17957418, -102.68544038,
         50.46429633,  240.1827698 ,   91.99801182, -201.85596577,
        272.61605203,   75.83561178,  -66.9230616 ,   -7.17970989,
         74.30449645,  160.85491767,  -37.16916411,  -60.94281496,
        -58.27180248,  -80.8057904 ,  -10.38438201,  -22.82507431,
        102.62147762,   33.55991177,  221.70894994,  163.54984913,
       -152.97414744])

In [22]:
(Y_test-Y_predict).std()

122.29540731358577

In [21]:
metrics.mean_squared_error(Y_test,Y_predict)

16181.102441096747

In [25]:
np.sqrt(metrics.mean_squared_error(Y_train,model.predict(X_train)))

2.406212873186352e-13

Regresja grzbietowa

In [26]:
x_all,y_all=datasets.make_regression(n_samples=50,n_features=50,n_informative=10)

In [27]:
x_all.shape

(50, 50)

In [28]:
y_all.shape

(50,)

In [29]:
X_train,X_test,Y_train,Y_test=model_selection.train_test_split(x_all,y_all,test_size=25)

In [30]:
X_train.shape

(25, 50)

In [31]:
model=linear_model.Ridge()

In [32]:
model.fit(X_train,Y_train)

Ridge()

In [33]:
Y_predict=model.predict(X_test)
Y_predict

array([-228.01109123,  -26.30861465, -375.148673  , -136.01748961,
       -100.33104701,  277.85111846,   76.25354168,  -63.53957642,
        -81.27514946,  -53.09997743,  148.74184406,   57.1849107 ,
        171.67887073, -253.94790581,   58.3817168 ,   46.19900363,
         31.80719314, -129.0780972 , -162.77696774,   67.41133735,
          4.84207129, -145.72008058,   78.10085426,  205.12206806,
       -182.1645949 ])

In [34]:
Y_test-Y_predict

array([ -44.70224532, -145.8285625 ,   28.31910135, -224.43347891,
         74.97854809,   96.75523573, -211.75819825,  -92.73259479,
          7.46768954, -127.04149217,  -39.37375799,   22.55283101,
         45.78535582,   54.86082255,  155.84867441,   99.9390191 ,
         38.11937889,  -54.77025992,  -41.88821954,  -29.65975572,
        -61.67260318,  208.39674344,   -4.58494367,  141.54016976,
       -150.73161505])

In [35]:
(Y_test-Y_predict).std()

108.62764518202333

In [36]:
metrics.mean_squared_error(Y_test,Y_predict)

11903.690688372148

In [37]:
np.sqrt(metrics.mean_squared_error(Y_train,model.predict(X_train)))

6.664700269023287

In [41]:
model.score(X_train,Y_train)

0.9991005499125584

Klasyfikacja

In [58]:
irys=datasets.load_iris() #wczytywanie danych

In [59]:
type(irys)

sklearn.utils.Bunch

In [60]:
print(irys)
x_all=irys.data
y_all=irys.target

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [61]:
X_train,X_test,Y_train,Y_test=model_selection.train_test_split(x_all,y_all)

In [62]:
X_train.shape

(112, 4)

In [70]:
model=linear_model.LogisticRegression()

In [69]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [68]:
Y_predict=model.predict(X_test)
Y_predict

array([0, 1, 0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 0, 2, 2, 2, 2, 1, 0, 1, 1, 1,
       2, 0, 1, 0, 0, 2, 2, 0, 1, 0, 1, 1, 0, 2, 2, 2])

In [56]:
Y_test-Y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
(Y_test-Y_predict).std()

0.0

In [72]:
print(metrics.classification_report(Y_test,Y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.92      1.00      0.96        11
           2       1.00      0.92      0.96        13

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



Model najbliższych sąsiadów

In [74]:
from sklearn import neighbors
irys=datasets.load_iris()

In [77]:
model=neighbors.KNeighborsClassifier(3)

In [79]:
x=0
y=2
model.fit(X_train[:,[x,y]],Y_train)

KNeighborsClassifier(n_neighbors=3)